# path to time series data file, input and target features should be in this file
timeseries_data_file: &timeseries_file
  - C:/Users/nguyenta/Documents/GitHub/HydroEcoLSTM_Lite/examples/1_streamflow_simulation/data/time_series.csv

# (optional input) path to catchment attributes file
static_data_file: &static_file
  - C:/Users/nguyenta/Documents/GitHub/HydroEcoLSTM_Lite/examples/1_streamflow_simulation/data/static_attributes.csv

# ouptut directory, model output will be save in this file
output_directory:
  - C:/Users/nguyenta/Downloads

# input static features - column name(s) of the static_data_file
input_static_features:
  - elev_mean
  - slope_mean
  - p_seasonality
  - aridity
  - pet_mean

# input timeseries features - column name(s) of the timeseries_data_file
input_timeseries_features:
  - precipitation_mm_d
  - temperature_mean_degC

# target output - column name(s) of the timeseries_data_file
target_features:
  - discharge_vol_m3_s

# selected catchments (object_id) used for traning/validation/test the model
id_train: &ids
  - a2009
  - 2016
  - 2018
  - 2019
  - 2020
  - 2024
  - 2030
  - 2033

id_valid: *ids

id_test: *ids

# start and ending of the train period, must be in yyyy-mm-dd hh:mm format
train_period: 
  - 2010-01-01 00:00
  - 2020-12-31 00:00

# start and ending of the validation period, must be in yyyy-mm-dd hh:mm format
valid_period: 
  - 2006-01-01 00:00
  - 2009-12-31 00:00

# start and ending of the test period, must be in yyyy-mm-dd hh:mm format
test_period: 
  - 2001-01-01 00:00
  - 2005-12-31 00:00

# Model head: currently only regression model (multi-layer neural network was implemented)
Regression:
  # Activation function of each layer (layer 1 - output layer): identity, relu, sigmoid, tanh, softplus
  activation_function:
    - identity
  # Number of neural each layer (number of neuraon in last layer = number of target features; put "None" for the last layer)
  num_neurons:
    - None
  # Number of layer
  num_layers: 1

# Scaler for input timeseries features: z_score, min_max, none
scaler_input_timeseries_features:
  - z_score
  
# Scaler for input static features: z_score, min_max, none
scaler_input_static_features:
  - z_score

# Scaler for target features: z_score, min_max, none
scaler_target_features:
  - min_max

# Hidden size of the LSTM network
hidden_size: 30

# Number of LSTM layers
num_layers: 1

# Number of training epoch
n_epochs: 1

# Learning rate
learning_rate: 0.001

# Dropout rate (applied to output of each LSTM layers)
dropout: 0

# Warmup length
warmup_length: 30

# Loss function: RMSE, MSE, MAE, NSE_complement
loss_function: NSE_complement

# Sequence length
sequence_length: 365

# Batch size
batch_size: 8

# Patience length
patience: 1

# (optional input) function to evaluate the selected model: NSE, RMSE, MAE, MSE
eval_function: NSE

# optional input - applied the selected model for prediction/ungagued catchments

# path to the static data file contains static features for inference catchments 
static_data_file_inference: *static_file

# path to the timeseries data file contains timeseries features for inference catchments 
timeseries_data_file_inference: *timeseries_file

# start and ending of the inference period, must be in yyyy-mm-dd hh:mm format
inference_period: 
  - 2001-01-01 00:00
  - 2009-12-31 00:00

# selected catchments (object_id) for inference
id_inference:
  - 2011
  - 2029

